name: split_payment_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_flavorizr: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flavorizr:
  flavors:
    development:
      app:
        name: "Development App"

      android:
        applicationId: "com.ioaholdings.mobile.dev"
        # firebase:
        #   config: ".firebase/development/google-services.json"
      ios:
        bundleId: "com.ioaholdings.mobile.dev" 
        # firebase:
        #   config: ".firebase/development/GoogleService-Info.plist"     
    production:
      app:
        name: "Production App"

      android:
        applicationId: "com.ioaholdings.mobile.prd"
        # firebase:
        #   config: ".firebase/production/google-services.json"
      ios:
        bundleId: "com.ioaholdings.mobile.prd"
        # firebase:
        #   config: ".firebase/production/GoogleService-Info.plist"