name: split_payment_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  # Flutter SDK
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  # the annotation package containing @riverpod
  riverpod_annotation: ^2.6.1

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Linting and Analysis
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: ^2.6.5
  very_good_analysis: ^6.0.0

  # Code Generation
  # a tool for running code generators
  build_runner: ^2.4.15
  # the code generator
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
